version: '3.8'

services:
  # Development services
  groundio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/web-app/node_modules
    ports:
      - "8081:8081"  # React Native Metro bundler
      - "3000:3000"  # Web development server
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - groundio-network

  # Database (if needed)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=groundio
      - POSTGRES_USER=groundio
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - groundio-network

  # Redis for caching (if needed)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - groundio-network

networks:
  groundio-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
